image: condaforge/mambaforge
tasks:
  - name: main setup
    before: |
      conda init
      mamba init
      source ~/.bashrc
      clear
      export CONDA_ENVS_DIRS=/workspace/envs
      export CONDARC=/workspace/.condarc
    init: |
      mamba env create -f config/environment.yml
      conda config --add channels defaults --file /workspace/.condarc
      conda config --add channels bioconda --file /workspace/.condarc
      conda config --add channels conda-forge --file /workspace/.condarc
    command: |
      mamba activate SER
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
